version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "semiannually"
    groups:
      dependencies:
        patterns: ["*"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "semiannually"
    groups:
      dependencies:
        patterns: ["*"]
