title: DoodleBobBuffPants
email: ajayseanx@gmail.com
description: >-
  
baseurl: ""
url: ""
github_username:  DoodleBobBuffPants

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
