name: Build

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'
      - run: yarn install --immutable
      - run: yarn lint:check
      - run: yarn test
      - run: yarn build
        env:
          BASE_PATH: /${{ github.event.repository.name }}/
